background: "#282828"
color: "#92A3B8"
border: "#9A7869"

menu:
  - key: "l"
    desc: Lock
    cmd: swaylock
  - key: "p"
    desc: Power off monitor and suspend
    cmd: swaylock & systemctl suspend-then-hibernate
  - key: "h"
    desc: Hibernate
    cmd: systemctl hibernate
  - key: "s"
    desc: Shutdown
    cmd: systemctl poweroff
