background: "#282828"
color: "#778293"
border: "#9763DC"

menu:
  - key: "l"
    desc: Lock
    cmd: swaylock
  - key: "p"
    desc: Power off monitor and suspend
    cmd: swaylock & systemctl suspend-then-hibernate
  - key: "h"
    desc: Hibernate
    cmd: systemctl hibernate
  - key: "s"
    desc: Shutdown
    cmd: systemctl poweroff
