format = """
[](fg:#7B7F6C)[ ](bg:#7B7F6C fg:#ffffff)$directory[](bg:#716B71 fg:#7B7F6C)$username[](bg:#367A8F fg:#716B71)$hostname[](fg:#367A8F)$cmd_duration$jobs$git_branch$git_metrics$git_status$fill$time$line_break$character
"""

command_timeout = 2000
scan_timeout = 500
add_newline = true

[character]
success_symbol = "[λ](bold #95373A)"
error_symbol = "[Δ](bold #367A8F)"

[directory]
truncation_length = 3
truncation_symbol = ".../"
read_only = "  "
style = "bg:#7B7F6C fg:#ffffff"
format = "[ $path ]($style)"

[fill]
symbol = " "

[cmd_duration]
min_time = 5
format = "[   $duration ](bold #ffffff)"

[hostname]
ssh_only = false
style = "bg:#367A8F fg:#ffffff"
format = "[ $hostname ]($style)"

[git_branch]
style = "fg:#ffffff"

[jobs]
symbol_threshold = 1
number_threshold = 2
symbol = "󱐌"
format = "[$symbol$number](bold #ffffff)"

[username]
show_always = true
style_user = "bg:#716B71 fg:#ffffff"
style_root = "bg:#554554 fg:#A29AA1"
format = "[ $user ]($style)"

[time]
disabled = false
format = "[$time](#ffffff)"
use_12hr = true
time_format = "%T"
utc_time_offset = "local"

[sudo]
symbol = " 󰐼 "
disabled = false
format = "[$symbol](bold #367A8F)"

[line_break]
disabled = false
