format = """
[](fg:#C289A4)[ ](bg:#C289A4 fg:#ffffff)$directory[](bg:#64676B fg:#C289A4)$username[](bg:#837572 fg:#64676B)$hostname[](fg:#837572)$cmd_duration$jobs$git_branch$git_metrics$git_status$fill$time$line_break$character
"""

command_timeout = 2000
scan_timeout = 500
add_newline = true

[character]
success_symbol = "[λ](bold #94758E)"
error_symbol = "[Δ](bold #837572)"

[directory]
truncation_length = 3
truncation_symbol = ".../"
read_only = "  "
style = "bg:#C289A4 fg:#ffffff"
format = "[ $path ]($style)"

[fill]
symbol = " "

[cmd_duration]
min_time = 5
format = "[   $duration ](bold #ffffff)"

[hostname]
ssh_only = false
style = "bg:#837572 fg:#ffffff"
format = "[ $hostname ]($style)"

[git_branch]
style = "fg:#ffffff"

[jobs]
symbol_threshold = 1
number_threshold = 2
symbol = "󱐌"
format = "[$symbol$number](bold #ffffff)"

[username]
show_always = true
style_user = "bg:#64676B fg:#ffffff"
style_root = "bg:#313845 fg:#90939A"
format = "[ $user ]($style)"

[time]
disabled = false
format = "[$time](#ffffff)"
use_12hr = true
time_format = "%T"
utc_time_offset = "local"

[sudo]
symbol = " 󰐼 "
disabled = false
format = "[$symbol](bold #837572)"

[line_break]
disabled = false
