# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #5488A6

background #000000
foreground #e0e0e0

color0 #413652
color1 #34445F
color2 #BBBDF7
color3 #3DB5EA
color4 #AC82E3
color5 #3482A9
color6 #3355EE
color7 #929BA9
color8 #767C85
color9 #34445F
color10 #BBBDF7
color11 #3DB5EA
color12 #AC82E3
color13 #3482A9
color14 #3355EE
color15 #929BA9

mark1_foreground #002BEA
mark2_foreground #5F7493
mark3_foreground #002BEA

