# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #AC7A7F

background #000000
foreground #e0e0e0

color0 #564C44
color1 #776A76
color2 #5B3351
color3 #596C5E
color4 #959989
color5 #AA5F61
color6 #5E95A5
color7 #B5AEB4
color8 #8D898D
color9 #776A76
color10 #5B3351
color11 #596C5E
color12 #959989
color13 #AA5F61
color14 #5E95A5
color15 #B5AEB4

mark1_foreground #2B778F
mark2_foreground #A27B9D
mark3_foreground #2B778F

