# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #81B4B4

background #000000
foreground #e0e0e0

color0 #5E4E51
color1 #5B5C69
color2 #5B8485
color3 #9293A9
color4 #A8717F
color5 #6FC0BC
color6 #F794A9
color7 #A6A7AD
color8 #848489
color9 #5B5C69
color10 #5B8485
color11 #9293A9
color12 #A8717F
color13 #6FC0BC
color14 #F794A9
color15 #A6A7AD

mark1_foreground #F56180
mark2_foreground #737799
mark3_foreground #F56180

